### ISSUE TITLE
Failure to compile with CUDA 7.0 + clang on OSX

### ISSUE THREAD

**Issue by mshabunin** [mshabunin/test2#149]
Converted from http://code.opencv.org/issues/4125
```
|| by Kevin Squire on 2015-01-16 02:19:00
|| Status: Open
|| Priority: Normal
|| Affected: branch 'master' (3.0-dev)
|| Target: 3.0
|| Category: gpu (cuda)

Failure to compile with CUDA 7.0 + clang on OSX
===========
When trying to compile OpenCV 3.0 (fresh github clone) on OSX with CUDA
7.0 (and clang, which is the default on OSX), I get the following error:

    /Users/kevin/src/opencv/opencv-git/modules/core/include/opencv2/core/cvstd.hpp(1048): error: "swap" is not a class or function template name in the current scope

Compiling is fixed by the following diff:

    diff --git a/modules/core/include/opencv2/core/cvstd.hpp b/modules/core/include/opencv2/core/cvstd.hpp
    index 0da8faf..8c2e96f 100644
    --- a/modules/core/include/opencv2/core/cvstd.hpp
    +++ b/modules/core/include/opencv2/core/cvstd.hpp
    @@ -1040,16 +1040,15 @@ static inline bool operator>= (const String& lhs, const char*   rhs) { return lh

     #ifndef OPENCV_NOSTL_TRANSITIONAL
     namespace std
    +{
    +    static inline void swap(cv::String& a, cv::String& b) { a.swap(b); }
    +}
     #else
     namespace cv
    -#endif
     {
    -    template<> inline
    -    void swap<cv::String>(cv::String& a, cv::String& b)
    -    {
    -        a.swap(b);
    -    }
    +    template<> inline void swap<cv::String>(cv::String& a, cv::String& b) { a.swap(b); }
     }
    +#endif

     #include "opencv2/core/ptr.inl.hpp" 

If this fix will work, I can submit a PR, but I highly suspect there is
a better fix.


History
=======
|| by Vladislav Vinogradov on 2015-01-16 12:31:00
Hello Kevin,

Thank you for you fix!   
Please submit a PR with your patch, so it can be tested by buildbot on
different configurations.

I think you can use

    static inline void swap(cv::String& a, cv::String& b) { a.swap(b); }

implementation for both cases (cv and std).

But it will be better to ask authors of opencv2/core/cvstd.hpp header in
GitHub Pull Request.
-   Assignee changed from Vladislav Vinogradov to Kevin Squire
-   Status changed from New to Open


|| by Maksim Shabunin on 2015-04-27 13:12:00
-   Target version changed from 3.0-beta to 3.0
```
